### CREATE CELEBRATION 

POST http://localhost:3000/api/celebration
content-type: application/json

{
    "title": "test",
    "description": "abc",
    "date": "01/01/2000",
    "address": {
        "zipCode": "11111111",
        "street": "fake",
        "number": 1
    }
}

### OPEN CELEBRATION

PATCH http://localhost:3000/api/celebration/e82667e6-d767-4185-a48d-e08a300d9fa1/open
content-type: application/json

### CONFIRM CELEBRATION

PATCH http://localhost:3000/api/celebration/e82667e6-d767-4185-a48d-e08a300d9fa1/confirm
content-type: application/json
